Frontview/urls.py
from rest_framework import routers
from django.urls import path
from .import views
router = routers.DefaultRouter()


app_name="frontview"

urlpatterns = [
    
    path('',views.homeView,name="homeView"), 
    path('cart',views.cartView,name="cartView"), 
    path('csales', views.customerOrderHistoryView, name="csales"),
    path('processorder',views.processPaymentView,name="processPaymentView"), 
    path('category/<str:cat>/<str:brand>/<str:p_type>',views.categoryView,name="categoryView"),
    path('details/<str:purchaseId>',views.saleView,name="saledetailsView"),
]
urlpatterns += router.urls

api/urls.py
from rest_framework import routers
from django.urls import path
from knox import views as KnoxView

from api.views import (Get_All, Get_Branch,processSalesView,
                       LoginUser,creditPaymentView,addProductView,
                       addStockView,PublishView)
router = routers.DefaultRouter()

app_name = 'api'

urlpatterns = [
    path('getall', Get_All.as_view(), name="get_all"),
    path('getbranch', Get_Branch.as_view(), name="get_branch"),
    path('logout', KnoxView.LogoutView.as_view(), name="knox_logout"),
    path('process',processSalesView.as_view(),name="processSalesView"),
    path('login', LoginUser.as_view(), name="login"),
    path('creditpayment',creditPaymentView.as_view(),name='creditPayment'),
    path('addproduct',addProductView.as_view(),name='addProductView'),
    path('addstock',addStockView.as_view(),name='addstockView'),
    path('publish',PublishView.as_view(),name='PublishView')
    
           
]

urlpatterns += router.urls

sales_and_stock/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('',include("Frontview.urls" , namespace='frontview')),
    path('admin/', admin.site.urls),
    path('logistics/',include("Logistics.urls" , namespace='logistics')),
    path('user/',include("User.urls" , namespace='user')),
    path('api/',include("api.urls" , namespace='api')),
    path('branch/',include("Branch.urls", namespace='branch')),
    path('product/',include("Product.urls",namespace='product')),
    path('badproduct/',include("Bad_Product.urls",namespace='bad_product')),
    path('returnedproduct/',include("Returned_Product.urls",namespace='returned_product')),
    path('stock/',include("Stock.urls",namespace='stock')),
    path('sales/',include("Sales.urls",namespace='sales')),
    path('credits/',include("Credit_Sales.urls",namespace='credit_sales')),
    path('password_reset/',auth_views.PasswordResetView.as_view(template_name="user/passwordreset.html"),name='password_reset',),
    path('password_reset_done/',auth_views.PasswordResetView.as_view(template_name="user/password_reset_done.html"),name="password_reset_done",),
    path('password_reset_confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name="user/password_reset_confirm.html"), name='password_reset_confirm',),
    path( 'password_reset_completed/',auth_views.PasswordResetCompleteView.as_view(template_name="user/password_reset_complete.html"), name='password_reset_complete',),

]

urlpatterns+=staticfiles_urlpatterns()

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# handler404 = 'errortemplate.views.page_not_found'
# handler403 = 'errortemplate.views.permission_denied'
# handler400 = 'errortemplate.views.bad_request'

Frontview/models.py
from django.db import models

# Create your models here.

User/models.py
from django.db import models
from django.contrib.auth.models import (BaseUserManager, AbstractBaseUser,PermissionsMixin)
from Branch.models import Branch

# Create your models here.

class UserManager(BaseUserManager):
    def create_user(self,email,full_name='null',phone_number=None,branch=None, password=None):
        if not email:
            raise ValueError('Users must have an email address')
        user = self.model(email=self.normalize_email(email),full_name=full_name,
                          phone_number=phone_number,branch=branch)
        user.set_password(password)
        user.save(using=self._db)
        return user
  
    def create_superuser(self, email, password):
        user = self.create_user(email,password=password,full_name="SITE CREATOR",)
        user.is_admin = True
        user.staff=True
        user.is_super_admin = True
        user.save(using=self._db)
        return user

class User(AbstractBaseUser,PermissionsMixin):
    full_name =models.CharField(verbose_name='full name', max_length=255)
    email = models.EmailField(verbose_name='email address',max_length=255,unique=True,)
    phone_number = models.CharField("phone_number", max_length=20,null=True,blank=True)
    branch = models.ForeignKey(Branch, verbose_name="branch", related_name="branch", on_delete=models.SET_NULL,null=True)
    is_super_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    staff=models.BooleanField(default=False)
    
    objects = UserManager()
    
    USERNAME_FIELD = 'email'
    
    def __str__(self):
        return self.full_name

    def has_perm(self, perm, obj=None):
        if not self.is_super_admin:
            if perm =="Users.add_user" or perm=="Users.change_user" or perm=="Users.delete_user":
                return False
            else:
                return True
        else:
            return True

    # remember to set appropriate permissions.
    def has_module_perms(self, app_label):
        if not self.is_super_admin:
            if app_label =="knox" or app_label=="auth" :
                return False
            else:
                return True
        else:
            return True
    @property

    def is_staff(self):
        return self.staff


class Customer(models.Model):
    """Model definition for Customer."""

    # TODO: Define fields here
    name = models.CharField(verbose_name='name', max_length=255)
    email = models.EmailField(verbose_name='email address',max_length=255,unique=True,)
    phone_number = models.CharField("phone_number", max_length=20,unique=True,)
    address = models.CharField(verbose_name="address", max_length=256)
    total_credit = models.IntegerField(verbose_name="total_credit",default=0)
    total_payment = models.IntegerField(verbose_name="total_payment",default=0)
    balance = models.IntegerField(verbose_name="total_balance",default=0)
    

    class Meta:
        """Meta definition for Customer."""

        verbose_name = 'Customer'
        verbose_name_plural = 'Customers'

    def __str__(self):
        """Unicode representation of Customer."""
        return f'{self.name} {self.phone_number}'

Frontview/views.py
import json
import requests
from django.urls import reverse
from django.conf import settings
from django.http import HttpResponseRedirect, JsonResponse
from django.core.mail import send_mail
from django.shortcuts import get_object_or_404, render
from Branch.models import Branch, Branch_Foot_Wear, Branch_Product, Branch_Suit, Branch_Tops, Foot_Wear_Size, Product_Size, Suit_Size, Tops_Size
from Logistics.models import Location
from Product.models import Category, Foot_Wear, Product, Product_Type, Size, Suit, Top
from Sales.models import Items, Sales
from User.models import Customer
from sales_and_stock.variables import official_email,rootUrl,admin_staff

from django.db.models.functions import Lower

# mapper = {'product':[Product],
#               'suits':[Suit],
#               'top':[Top],
#               'foot_wear':[Foot_Wear],
#               }
mapper = {'product':[Product,Branch_Product,Product_Size],
              'suits':[Suit,Branch_Suit,Suit_Size],
              'top':[Top,Branch_Tops,Tops_Size],
              'foot_wear':[Foot_Wear,Branch_Foot_Wear,Foot_Wear_Size],
    
              }
# Create your views here.
def homeView(request):
    products_list = []   
    sizes = []
    for pgroup in mapper.values():
        products = pgroup[0].objects.filter(publish=True)[:10]
        if products:
            products_list.append(products)
            
            for product in products:
                filtered_sizes = []
                branch_product = pgroup[1].objects.get(branch__name='Main',
                                                            product = product)
                for size in product.sizes.all():
                    qty =  pgroup[2].objects.get(branch_instance=branch_product,
                                                        size = size).current_qty
                    if qty >= 0:
                        filtered_sizes.append(size)
                sizes.append(filtered_sizes)
        
    return render(request,'frontview/home.html',{"products_list":zip(products_list,sizes)})

def cartView(request): 
    locations = Location.objects.all()
    return render(request,'frontview/cart.html',{"public_key":settings.PAYSTACT_PUBLIC_KEY,
                                                 "locations":locations})

def categoryView(request,cat,brand,p_type):
    brand = brand.replace('_',' ').replace('%20',' ').replace('-',' ').strip()
    p_type = p_type.replace('_',' ').replace('%20',' ').replace('-',' ').strip()
    cat = cat.replace('_',' ').replace('%20',' ').replace('-',' ').strip()
    sizes = []
    
    if brand == 'None':
        brand = None   
    
    category = get_object_or_404(Category,name__iexact=cat)
    product_type = Product_Type.objects.filter(category=category)[0]
    pgroup = product_type.p_group
    
    if brand == 'default' and p_type == 'default':
        p_type = mapper[pgroup][0].objects.filter(publish=True,product_type__category=category)[0]
        p_type = Product_Type.objects.get(id=p_type.product_type.id)
        
        brand = mapper[pgroup][0].objects.filter(publish=True,product_type__category=category,product_type = p_type.id)[0]
        brand = brand.brand
    elif brand != 'default' and p_type != 'default':
        p_type = Product_Type.objects.get(name=p_type,category = category)
       
    elif  p_type != 'default':
        p_type = Product_Type.objects.get(name=p_type,category = category)
        
        brand = mapper[pgroup][0].objects.filter(publish=True,product_type__category=category,product_type = p_type.id)[0]
        brand = brand.brand
    elif brand != 'default':
        p_type = mapper[pgroup][0].objects.filter(publish=True,product_type__category=category)[0]
        p_type = Product_Type.objects.get(id=p_type.product_type.id)
 
    products = mapper[pgroup][0].objects.filter(publish=True,product_type__category=category,brand=brand,product_type=p_type.id)
    for product in products:
            filtered_sizes = []
            branch_product = mapper[pgroup][1].objects.get(branch__name='Main',
                                                            product = product)
            for size in product.sizes.all():
                qty =  mapper[pgroup][2].objects.get(branch_instance=branch_product,
                                                        size = size).current_qty
                if qty <=0:
                    filtered_sizes.append(size)
            sizes.append(filtered_sizes)
    
    if not products:
        # try a randon brand
        brand = mapper[pgroup][0].objects.filter(publish=True,product_type__category=category,product_type = p_type.id)[0]
        brand = brand.brand
        products = mapper[pgroup][0].objects.filter(publish=True,product_type__category=category,brand=brand,product_type=p_type.id)
        
   
    brands = mapper[pgroup][0].objects.filter(publish=True,product_type__category=category,product_type=p_type.id).annotate(lower = Lower('brand')).values_list('lower',flat=True)
    distincts = mapper[pgroup][0].objects.filter(publish=True,product_type__category=category).values_list('product_type').distinct()
    product_types = Product_Type.objects.filter(id__in = distincts)
   
    brands = set(brands)
    
    
    # unsorted_product_types = Product_Type.objects.filter(category=category.id,
    #                                                         product_type__publish = True)
    # sorted_product_types = []
    # for product_type in unsorted_product_types:
    #     if product_type not in sorted_product_types:
    #         sorted_product_types.append(product_type) 
            
    return render(request,'frontview/category.html',{"category":category,
                                                     "products":zip(products,sizes),
                                                     'brands' :brands,
                                                     'product_types':product_types,
                                                      'p_type':p_type.name,
                                                      'brand_': brand})
    
    
def processPaymentView(request):
       if request.method == "POST":
           customer_instance = None
           sales = None
           sale_type = None
           data = json.loads(request.body.decode("utf-8"))
           
           if data['action'] == "payment":

               headers = {
                    "Authorization": f'Bearer {settings.PAYSTACT_SECRET_KEY}',
                        'Content-Type': 'application/json',
                }
               url = f'https://api.paystack.co/transaction/verify/{data["purchase_id"]}'
                
               response = requests.get(url,headers=headers)
                
               if response.status_code == 200:
                #    response_data = response.json()
                   sales = Sales.objects.get(purchase_id=data["purchase_id"])
                   sales.paid = True
                   sales.save()
                #    email_body = (f"There is a new online sale with ID:{sales.purchase_id}. Please, view " +
                #         f"sales details on {rootUrl}/sales/sale/{sales.purchase_id}/{sales.payment_method} ")
                #    send_mail('A new order',email_body,official_email,[admin_staff])
                   return JsonResponse({"message":'success'})
                        
           if data['action'] == "create":
               
                orderlist = data['orders']
                
                try:
                    customer_instance = Customer.objects.get(phone_number = data['phone_number'])
                    customer_instance.phone_number = data["phone_number"]
                    customer_instance.email = data["email"]
                    customer_instance.name = data["name"]
                    customer_instance.address = data["address"]
                    customer_instance.save()
                except Customer.DoesNotExist:
                        customerData = {"phone_number":data["phone_number"], "email":data["email"],
                                "name":data["name"],"address":data["address"]}
                        customer_instance = Customer.objects.create(**customerData)
                
                branch = Branch.objects.get(branch__is_super_admin = True)
                sales = Sales.objects.create(branch=branch,
                                                    total_amount=data['total_amount'],
                                                    expected_amount=data['expected_amount'],
                                                    logistics=data['logistics'],
                                                    destination=data['address'],
                                                    remark = data['remark'],
                                                    channel ="web",
                                                    customer = customer_instance,
                                                    payment_method = data['payment_method'],
                                                    purchase_id = data['purchase_id'],
                                                    paid=False)
                
                for item in orderlist:
            
                    pgroup = item['pgroup']
                    product = mapper[pgroup][0].objects.get(pk=int(item['id']))
                    size= None
                    
                    if item['id'] != item['Id']:
                        _,sizeId= item['Id'].split("_")
                        size = Size.objects.get(pk=int(sizeId))
                        
                        
                    if pgroup == 'suits':
                        pgroup = 'suit'
                        Item =  Items.objects.create(suit=product,product_type=item['product_type'],
                                                    p_group = pgroup,size_instance=size,
                                                    qty=item['qty'],

Frontview/templates/frontview/cart.html
{% extends 'frontview/home.html' %} {% load static %} {% block styles %}
<link rel="stylesheet" type="text/css" href="{% static 'CSS/homeproductpage.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'CSS/general.css' %}"> {% endblock styles %} {% block title %}

<title>Cart</title>{% endblock title %}{% block banner %}{% endblock banner %} {% block main %}

<h1>CART</h1>

<div id="confirmBox">
    <p>Are you Sure you want to delete?</p>
    <div style="text-align: center;">
        <a href="" class="cancelDelete">Cancel</a>
        <a href="" class="confirmDelete">Delete</a>
    </div>
</div>

<div class="historyDiv">
    <form action="{% url 'frontview:csales'%}" method="post">
        {% csrf_token %}
        <input type="hidden" id="hidden_phone_number" name="phone_number">
        <button type="submit">Order History</button>
    </form>
</div>

<div class="cartbody">
    <p style="display: none;text-align:center" class="emptycart">Your cart is empty.</p>
    <div id="cartflex">

    </div>
    <div style="margin: 30px auto; display:flex;justify-content: space-around;flex-wrap: wrap;">
        <p style="display:none;padding:0px 10px 5px 10px;"><strong>Total: &#8358 <span id="total"></span></strong></p>
        <p style="display:none;padding:0px 10px 5px 10px;"><strong>Logistics: &#8358 <span id="ltotal"></span></strong></p>
        <p><strong> Grand Total: &#8358 <span id="grand_total"></span></strong></p>
    </div>

    <button id="process_order" class="addbutton">Process Order</button>
    <div id="customerDetails">
        <div>
            <label for="logistics">Delivery Logistics</label>
            <select style="padding: 5px;text-align:center" name="logistics" id="logistics">
            <option  value="0">---Please Select---</option>
            {% for location in locations  %}
            <option value="{{location.price}}">{{location.location}} -- &#8358 <span class="amount">{{location.price}}</span></option>  
            {% endfor %}
        </select>
        </div>
        <div class="customerDetails">
            <form name="customerForm" action="" method="post">
                {% csrf_token %}
                <fieldset>
                    <legend>Customer Details</legend>
                    <label for="id_name">Name:</label>
                    <p id="nameer"></p>
                    <input class="contactInput" type="text" name="name" maxlength="255" required="" id="id_name">
                    <label for="id_email">Email address:</label>
                    <p id="emailer"></p>
                    <input type="email" class="contactInput" name="email" maxlength="255" required="" id="id_email">
                    <label for="id_phone_number">Phone_number:</label>
                    <p id="phone_numberer"></p>
                    <input type="text" class="contactInput" name="phone_number" maxlength="20" required="" id="id_phone_number">
                    <label for="id_address">Address:</label>
                    <p id="addresser"></p>
                    <input type="text" class="contactInput" name="address" maxlength="256" required="" id="id_address">
                </fieldset>
            </form>
        </div>
        <p id="public_key" style="display: none;">{{public_key}}</p>
        <div class="make_payment">
            <button id="make_payment" style="margin: 30px auto;" class="addbutton">Make Payment</button>
        </div>
    </div>
</div>
{% endblock main %} {% block javascript %}
<script src="{% static 'javascript/state.js' %}"></script>
<script src="{% static 'javascript/homeproductpage.js' %}"></script>
<script src="https://js.paystack.co/v1/inline.js"></script>
<script src="{% static 'javascript/cart.js' %}"></script>


{% endblock javascript %}

</html>

Frontview/templates/frontview/orderhistory.html
 {% extends 'frontview/home.html' %} {% load static %} {% block styles %}
<link rel="stylesheet" type="text/css" href="{% static 'CSS/homeproductpage.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'CSS/general.css' %}"> {% endblock styles %} {% block title %}
<title>Order history</title>
{% endblock title %} {% block banner %} {% endblock banner %} {% block main %}
<h1>ORDER HISTORY</h1>
<section class="orderhistory">
    {% csrf_token %} {% for order in orders %}
    <div class="order">
        <p class="center"> <a style="color: blue;" href="{% url 'frontview:saledetailsView' order.purchase_id %}">{{order.purchase_id}}</a></p>
        <p>Total: &#8358 <span class="amount"> {{order.total_amount|add:order.logistics}}</span></p>
        <p>{{order.date}}</p>
        <p>Channel: {{order.channel}}</p>
        {% if order.paid %}
        <p class="center">Paid</p>
        {% else %}
        <p id="data{{order.id}}" style="display: none;">{{order.purchase_id}};{{order.total_amount|add:order.logistics}};{{order.customer.email}}</p>
        <button style="color: white;background-color: green;
            border-color: white;" id="{{order.id}}" class="make_payment center">Pay Now</button> {% endif %}

    </div>
    {% endfor %}
    <p id="public_key" style="display: none;">{{public_key}}</p>
</section>
{% endblock main %} {% block javascript %}
<script src="{% static 'javascript/state.js' %}"></script>
<script src="{% static 'javascript/homeproductpage.js' %}"></script>
<script src="https://js.paystack.co/v1/inline.js"></script>
<script src="{% static 'javascript/salesdetail.js' %}"></script>
{% endblock javascript %}

Frontview/templates/frontview/saledetails.html
{% extends 'frontview/home.html' %} {% load static %} {% block styles %}
<link rel="stylesheet" type="text/css" href="{% static 'CSS/homeproductpage.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'CSS/general.css' %}"> {% endblock styles %} {% block title %}

<title>Order history</title>{% endblock title %}{% block banner %}{% endblock banner %} {% block main %}
<div class="historyDiv">
    <form action="{% url 'frontview:csales'%}" method="post">
        {% csrf_token %}
        <input type="hidden" id="hidden_phone_number" name="phone_number">
        <button type="submit">Order History</button>
    </form>
</div>

<div>
    <div class="customerData">
        <p><strong>Name:</strong> {{customer.name}}</p>
        <p><strong>Phone Number:</strong> {{customer.phone_number}}</p>
        <p><strong>Email:</strong> {{customer.email}}</p>
        <p><strong>Address:</strong> {{customer.address}}</p>
        <p><strong>Purchase_id:</strong> {{sale.purchase_id}}</p>
        <p><strong>Payment_method:</strong> {% if sale.payment_method %} {{sale.payment_method}}{% else %} Credit {% endif %}</p>
        <p><strong>Remark: </strong>{{sale.remark}}</p>
        <p><strong>Date:</strong> {{sale.date}}</p>
        <p><strong>Paid: </strong> {{sale.paid}} </p>
    </div>

    <div id="salesList">
        <table>
            <thead>
                <tr>
                    <th>SN</th>
                    <th>Product</th>
                    <th>Category</th>
                    <th>Brand</th>
                    <th>size</th>
                    <th>Color</th>
                    <th>Product meta</th>
                    <th>Size</th>
                    <th>Unit Price</th>
                    <th>Qty</th>
                    <th>Total Price</th>
                    <th>Logistics</th>

                </tr>
            </thead>
            <tbody id="tbody">
                {% for item in sale.items.all %}
                <tr>
                    <td>{{forloop.counter}}</td>
                     <td>{{item.get_product.product_type.category}}</td>
                    <td>{{item.get_product.product_type.name}}</td>
                    <td>{{item.get_product.brand}}</td>
                    <td>{{item.size_instance.size}}</td>
                    <td>{{item.get_product.color}}</td>
                    <td style="font-size: 14px;">{{item.get_product.get_details}}</td>
                    <td>{{item.size_instance.size}} </td>
                    <td class="amount">{{item.unit_price}}</td>
                    <td>{{item.qty}} </td>
                    <td class="amount">{{item.total_price}}</td>
                    <td></td>
                </tr>

                {% endfor %}
            </tbody>
            <tfoot>
                <tr>
                    <td></td>
                    <td colspan="9">Total</td>
                    <td id="grandtotal" class="amount">{{sale.total_amount}}</td>
                    <td id="logistics" class="amount">{{sale.logistics}}</td>
                </tr>
                <tr>
                    <td></td>
                    <td colspan="9">Grand Total</td>
                    <td colspan="2" id="logistics" class="amount">{{sale.logistics|add:sale.total_amount}}</td>
                </tr>
            </tfoot>
        </table>
    </div>
</div>

{% endblock main %} {% block javascript %}
<script src="{% static 'javascript/state.js' %}"></script>
<script src="{% static 'javascript/homeproductpage.js' %}"></script>
<!-- <script src="{% static 'javascript/history.js' %}"></script> -->



{% endblock javascript %}

Frontview/templates/frontview/slide_category.html
{% load static %}
<div class="slider">
    <div class="slides">
        <input type="radio" name="radio_btn" onclick="handleClick(this)" id="radio1">
        <input type="radio" name="radio_btn" onclick="handleClick(this)" id="radio2">
        <input type="radio" name="radio_btn" onclick="handleClick(this)" id="radio3">
        <input type="radio" name="radio_btn" onclick="handleClick(this)" id="radio4">

        <div class="slide first" id="1">
            <a class="catlink" href="{% url 'frontview:categoryView' 'suit' 'default' 'default' %}"> Suits</a>
            <a class="catlink2" href="{% url 'frontview:categoryView' 'suit' 'default' 'default' %}">Shop Category</a>
            <img src="{% static 'CSS/slide_img/suits.jpg' %}" alt="Suits image" />
        </div>

        <div class="slide" id="2">
            <a class="catlink" href="{% url 'frontview:categoryView' 'shoe' 'default' 'default' %}"> Shoes</a>
            <a class="catlink2" href="{% url 'frontview:categoryView' 'shoe' 'default' 'default' %}">Shop Category</a>
            <img src="{% static 'CSS/slide_img/shoes.jpg' %}" alt=" Shoes image" />
        </div>

        <div class="slide" id="3">
            <a class="catlink" href="{% url 'frontview:categoryView' 'shirt' 'default' 'default' %}">Shirts</a>
            <a class="catlink2" href="{% url 'frontview:categoryView' 'shirt' 'default' 'default' %}">Shop Category</a>
            <img src="{% static 'CSS/slide_img/shirts.jpg' %}" alt="Shirts image" />
        </div>

        <div class="slide" id="4">
            <a class="catlink" href="{% url 'frontview:categoryView' 'bag' 'default' 'default' %}">Bags</a>
            <a class="catlink2" href="{% url 'frontview:categoryView' 'bag' 'default' 'default' %}">Shop Category</a>
            <img src="{% static 'CSS/slide_img/box.jpg' %}" alt="Travelling Boxes image" />
        </div>

        <div class="navigation-auto">
            <div class="auto-btn1"></div>
            <div class="auto-btn2"></div>
            <div class="auto-btn3"></div>
            <div class="auto-btn4"></div>
        </div>

    </div>

    <div class="navigation-manual">
        <label for="radio1" class="manual-btn"></label>
        <label for="radio2" class="manual-btn"></label>
        <label for="radio3" class="manual-btn"></label>
        <label for="radio4" class="manual-btn"></label>
        <!-- <label for="radio5" class="manual-btn"></label> -->
    </div>

</div>

<script>
    let counter = 1
    const handleLinkDisplay = (num, auto = true) => {
        if (!auto) {
            counter = num


        }
        let arr;
        switch (num) {
            case 1:
                arr = [2, 3, 4]
                break;
            case 2:
                arr = [1, 3, 4]
                break;
            case 3:
                arr = [2, 1, 4]
                break;
            case 4:
                arr = [2, 3, 1]
                break;

        }

        let inVeiw = document.getElementById(num)
        let incatlinks = inVeiw.getElementsByTagName("a")
        let catlink2 = inVeiw.getElementsByClassName('catlink2')[0]

        let inVeiwWidth = inVeiw.clientWidth
        let inVeiwHeight = inVeiw.clientHeight

        for (id of arr) {
            let outVeiw = document.getElementById(id)
            let catlinks = outVeiw.getElementsByTagName("a")
            for (link of catlinks) {
                link.style.display = 'none'
            }
        }

        setTimeout(() => {
            for (link of incatlinks) {
                link.style.display = 'block'
            }
            let left = (inVeiwWidth - catlink2.offsetWidth) / 2
            let top = (inVeiwHeight - catlink2.offsetHeight) / 2
            catlink2.style.marginLeft = left + 'px'
            catlink2.style.marginTop = top + 'px'
        }, 1500)

    }

    handleLinkDisplay(counter)
    setInterval(() => {
        document.getElementById('radio' + counter).checked = true;
        handleLinkDisplay(counter)
        counter++
        if (counter > 4) {
            counter = 1
        }
    }, 5000)

    const handleClick = (elem) => {
        const slides = document.getElementsByName('slide')
        for (slide of slides) {
            slide.style.display = "none"
        }
        handleLinkDisplay(parseInt(elem.id[5]), false)
    }
</script>