Bad_Product/urls.py
from rest_framework import routers
from knox import views as KnoxView
from django.urls import path
from .import views
router = routers.DefaultRouter()


app_name="badproduct"

urlpatterns = [  
    path('<int:badProductId>/<str:action>/<str:pgroup>',views.badProductView,name="badProductView"),  

]
urlpatterns += router.urls

Logistics/urls.py
from rest_framework import routers
from django.urls import path
from .import views
router = routers.DefaultRouter()


app_name="logistics"

urlpatterns = [ 
    path('location/<int:locationId>/<str:action>',views.locationView,name="locationView"), 
    
]
urlpatterns += router.urls

Product/urls.py
from rest_framework import routers
from knox import views as KnoxView
from django.urls import path
from .import views
router = routers.DefaultRouter()


app_name="product"

urlpatterns = [ 
    path('cat/<int:categoryId>/<str:action>',views.categoryView,name="categoryView"), 
    path('producttype/<int:productTypeId>/<str:action>',views.productTypeView,name="productTypeView"), 
    path('size/<int:sizeId>/<str:action>',views.sizeView,name="sizeView"),
    path('product/<int:productId>/<str:action>/<str:pgroup>',views.productView,name="productView"),  
    # path('returnedproduct/<int:returnedProductId>/<str:action>',views.returnedProductView,name="returnedProductView"),  

]
urlpatterns += router.urls

Sales/urls.py
from rest_framework import routers
from django.urls import path

from .import views
router = routers.DefaultRouter()


app_name="sales"

urlpatterns = [ 
    path('',views.salesView,name="salesView"), 
    path('process',views.processSalesView,name="processSalesView"),
    path('<int:productTypeId>/<str:pgroup>/<str:brand>',views.salesProductView,name="salesProductView"),
    path('sale/<str:purchaseId>/<str:type>',views.saleView,name="saleView"), 
    path('analysis/<int:branchID>/<str:date>/',views.salesAnalysisView,name="salesAnalysisView"),
    path('<str:start_date>/<str:end_date>/<int:branchID>/rangeanalysis',views.rangeSalesView,name="rangeSalesView"),

]
urlpatterns += router.urls

Stock/urls.py
from rest_framework import routers
from django.urls import path
from .import views
router = routers.DefaultRouter()


app_name="stock"

urlpatterns = [ 
    path('getstock',views.getStockView,name="getStockView"),
    path('stock/<int:stockId>/<int:branchId>/<str:action>/<str:pgroup>',views.stockView,name="stockView"), 

]
urlpatterns += router.urls

User/urls.py
from django.urls import path
from .import views


app_name="user"

urlpatterns = [
    path('login/',views.loginView,name="loginView"),
    path('login/<path:next>',views.loginView,name="loginRedirect"),
    path('logout',views.logoutView,name="logoutView"), 
    # path('<str:fullname>/dashboardView',views.dashboardView,name="dashboardView"),  
    path('user/<int:userId>/<str:action>',views.userView,name="userView"), 
    path('customer/<int:customerId>/<str:action>',views.customerView,name="customerView"),

]

api/urls.py
from rest_framework import routers
from django.urls import path
from knox import views as KnoxView

from api.views import (Get_All, Get_Branch,processSalesView,
                       LoginUser,creditPaymentView,addProductView,
                       addStockView,PublishView)
router = routers.DefaultRouter()

app_name = 'api'

urlpatterns = [
    path('getall', Get_All.as_view(), name="get_all"),
    path('getbranch', Get_Branch.as_view(), name="get_branch"),
    path('logout', KnoxView.LogoutView.as_view(), name="knox_logout"),
    path('process',processSalesView.as_view(),name="processSalesView"),
    path('login', LoginUser.as_view(), name="login"),
    path('creditpayment',creditPaymentView.as_view(),name='creditPayment'),
    path('addproduct',addProductView.as_view(),name='addProductView'),
    path('addstock',addStockView.as_view(),name='addstockView'),
    path('publish',PublishView.as_view(),name='PublishView')
    
           
]

urlpatterns += router.urls

sales_and_stock/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('',include("Frontview.urls" , namespace='frontview')),
    path('admin/', admin.site.urls),
    path('logistics/',include("Logistics.urls" , namespace='logistics')),
    path('user/',include("User.urls" , namespace='user')),
    path('api/',include("api.urls" , namespace='api')),
    path('branch/',include("Branch.urls", namespace='branch')),
    path('product/',include("Product.urls",namespace='product')),
    path('badproduct/',include("Bad_Product.urls",namespace='bad_product')),
    path('returnedproduct/',include("Returned_Product.urls",namespace='returned_product')),
    path('stock/',include("Stock.urls",namespace='stock')),
    path('sales/',include("Sales.urls",namespace='sales')),
    path('credits/',include("Credit_Sales.urls",namespace='credit_sales')),
    path('password_reset/',auth_views.PasswordResetView.as_view(template_name="user/passwordreset.html"),name='password_reset',),
    path('password_reset_done/',auth_views.PasswordResetView.as_view(template_name="user/password_reset_done.html"),name="password_reset_done",),
    path('password_reset_confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name="user/password_reset_confirm.html"), name='password_reset_confirm',),
    path( 'password_reset_completed/',auth_views.PasswordResetCompleteView.as_view(template_name="user/password_reset_complete.html"), name='password_reset_complete',),

]

urlpatterns+=staticfiles_urlpatterns()

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# handler404 = 'errortemplate.views.page_not_found'
# handler403 = 'errortemplate.views.permission_denied'
# handler400 = 'errortemplate.views.bad_request'

Product/forms.py
from django import forms
from Branch.models import Branch

from Product.models import  Category, Foot_Wear, Product, Product_Type, Size, Suit, Top

class CategoryForm(forms.ModelForm):
    """Form definition for Category."""

    class Meta:
        """Meta definition for Categoryform."""

        model = Category
        fields = '__all__'
        

class SizeForm(forms.ModelForm):
    """Form definition for Size."""

    class Meta:
        """Meta definition for Sizeform."""

        model = Size
        fields = '__all__'

        
class ProductTypeForm(forms.ModelForm):
    """Form definition for Product_Type."""

    class Meta:
        """Meta definition for Product_Typeform."""

        model = Product_Type
        fields = '__all__'
        
class ProductForm(forms.ModelForm):
    """Form definition for Product."""
    sizes = forms.ModelMultipleChoiceField(widget=forms.CheckboxSelectMultiple,
                                                queryset=Size.objects.all(),required=False)
    
    class Meta:
        """Meta definition for Productform."""

        model = Product
        fields = '__all__'
        
class SuitForm(forms.ModelForm):
    """Form definition for Suit."""
    sizes = forms.ModelMultipleChoiceField(widget=forms.CheckboxSelectMultiple,
                                                queryset=Size.objects.all(),
                                                required=False)
    
    class Meta:
        """Meta definition for Suitform."""

        model = Suit
        fields = '__all__'
        
class TopForm(forms.ModelForm):
    """Form definition for Top."""
    sizes = forms.ModelMultipleChoiceField(widget=forms.CheckboxSelectMultiple,
                                                queryset=Size.objects.all(),required=False)
    
    class Meta:
        """Meta definition for Topform."""

        model = Top
        fields = '__all__'
    
class FootWearForm(forms.ModelForm):
    """Form definition for FootWear."""
    sizes = forms.ModelMultipleChoiceField(widget=forms.CheckboxSelectMultiple,
                                                queryset=Size.objects.all(),required=False)
    
    class Meta:
        """Meta definition for FootWearform."""

        model = Foot_Wear
        fields = '__all__'

Sales/forms.py
from django import forms
from Sales.models import Sales


class salesForm(forms.ModelForm):
    """Form definition for sales."""

    class Meta:
        """Meta definition for salesform."""

        model = Sales
        fields = ('payment_method','remark')
        widgets = {
            "remark" : forms.widgets.Textarea()     
            }

Product/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from Branch.models import Branch, Product_Size
from Product.forms import  CategoryForm, FootWearForm, ProductForm, ProductTypeForm,  SizeForm, SuitForm, TopForm
from Product.models import Category, Foot_Wear, Product, Product_Type, Size, Suit, Top

# Create your views here.
@login_required(login_url="user:loginView")
def categoryView(request,categoryId,action):
    
    # categories = Category.objects.all()
    
    if categoryId != 0:   
        category_instance = Category.objects.get(id=categoryId)
    
    if request.method == "POST" and action == "add":
        form = CategoryForm(data= request.POST,files=request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('product:categoryView',
            kwargs={"action":"view","categoryId":0}))
        else:
            return render(request,"product/category.html",
                  {"form":form,"categoryId":0})  
            
    if action == "edit":
        if request.method == "POST":
            form = CategoryForm(data= request.POST,files=request.FILES,instance=category_instance)
         
            if form.is_valid():
                form.save()
                return HttpResponseRedirect(reverse('product:categoryView',
                        kwargs={"action":"view","categoryId":0}))
            else:
                return render(request,"product/category.html",
                  {"form":form,"categoryId":category_instance.id})
        else:
            return render(request,"product/category.html",
                  {"form":CategoryForm(instance=category_instance),
                   "categoryId":category_instance.id,"action":"edit",
                #    'categories':categories
                   })
    
    if action == "delete":
        category_instance.delete()
        return HttpResponseRedirect(reverse('product:categoryView',
            kwargs={"action":"view","categoryId":0}))
                 
    return render(request,"product/category.html",
                  {"form":CategoryForm(),"categoryId":0, 
                #    'categories':categories,
                   "action":"add"})
    

@login_required(login_url="user:loginView")
def productTypeView(request,productTypeId,action):
    
    productTypes = Product_Type.objects.all()
    
    if productTypeId != 0:   
        product_type_instance = Product_Type.objects.get(id=productTypeId)
    
    if request.method == "POST" and action == "add":
        form = ProductTypeForm(data= request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('product:productTypeView',
            kwargs={"action":"view","productTypeId":0}))
        else:
            return render(request,"product/product_type.html",
                  {"form":form,"productTypeId":0,"action":"view"})  
            
    if action == "edit":
        if request.method == "POST":
            form = ProductTypeForm(data= request.POST,instance=product_type_instance)
            if form.is_valid():
                form.save()
                return HttpResponseRedirect(reverse('product:productTypeView',
                        kwargs={"action":"view","productTypeId":0}))
            else:
                return render(request,"product/product_type.html",
                  {"form":form,"productTypeId":product_type_instance.id})
        else:
            return render(request,"product/product_type.html",
                  {"form":ProductTypeForm(instance=product_type_instance),
                   "productTypeId":product_type_instance.id,"action":"edit",'productTypes':productTypes})
    
    if action == "delete":
        product_type_instance.delete()
        return HttpResponseRedirect(reverse('product:productTypeView',
            kwargs={"action":"view","productTypeId":0}))
                 
    return render(request,"product/product_type.html",
                  {"form":ProductTypeForm(),"productTypeId":0, 'productTypes':productTypes,"action":"add"})
  
    
@login_required(login_url="user:loginView")  
def sizeView(request,sizeId,action):
    
    sizes = Size.objects.all()
    form = SizeForm()
    
    if sizeId != 0:   
        size_instance = Size.objects.get(id=sizeId)
       
    
    if request.method == "POST" and action == "add":
        form = SizeForm(data= request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('product:sizeView',
            kwargs={"action":"view","sizeId":0}))
        else:
            return render(request,"product/size.html",
                  {"form":form,"sizeId":0,"action":"view"})  
            
    if action == "edit":
        if request.method == "POST":
            form = SizeForm(data= request.POST,instance=size_instance)
            if form.is_valid():
                form.save()
                return HttpResponseRedirect(reverse('product:sizeView',
                        kwargs={"action":"view","sizeId":0}))
            else:
                return render(request,"product/size.html",
                  {"form":form,"sizeId":size_instance.id,"action":"edit",'sizes':sizes})
        else:
            return render(request,"product/size.html",
                  {"instance":size_instance,
                   "sizeId":size_instance.id,"action":"edit",'sizes':sizes})
    
    if action == "delete":
        size_instance.delete()
        return HttpResponseRedirect(reverse('product:sizeView',
            kwargs={"action":"view","sizeId":0}))
                 
    return render(request,"product/size.html",
                  {"form":form,"sizeId":0, 'sizes':sizes,"action":"add"})
    

@login_required(login_url="user:loginView")
def productView(request,productId,action,pgroup):
    mapper = {'product':[Product,ProductForm],
              'suits':[Suit,SuitForm],
              'top':[Top,TopForm],
              'foot_wear':[Foot_Wear,FootWearForm],
    
              }
    
    form = mapper[pgroup][1]()
    
    if productId != 0:   
        product_instance = mapper[pgroup][0].objects.get(id=productId)
        form = mapper[pgroup][1](instance=product_instance)
        
    if request.method == "POST" and action == "add":
        form = mapper[pgroup][1](data= request.POST,files=request.FILES)
        if form.is_valid():
            form.save()
            # product.sizes.all()
            return HttpResponseRedirect(reverse('product:productView',
            kwargs={"action":"view","productId":0,'pgroup':pgroup}))
        else:
            return render(request,"product/product.html",
                  {"form":form,"productId":0,"action":"add",
                   'pgroup':pgroup})  
            
    if action == "edit" and request.method == "POST":
            
        form = mapper[pgroup][1](data= request.POST,files=request.FILES,instance=product_instance)
        if form.is_valid():
            form.save()

            return HttpResponseRedirect(reverse('product:productView',
                        kwargs={"action":"view","productId":0,'pgroup':pgroup}))
        else:
            return render(request,"product/product.html",
                  {"form":form,"productId":product_instance.id,
                   "action":"edit",'pgroup':pgroup})
    elif action == "edit" and request.method == "GET":
        return render(request,"product/product.html",
                  {"product_instance":product_instance,
                   "productId":product_instance.id,"action":"edit",
                   'form':form,
                    'pgroup':pgroup})
    
    if action == "delete":
        product_instance.delete()
        return HttpResponseRedirect(reverse('product:productView',
            kwargs={"action":"view","productId":0,'pgroup':pgroup}))
                 
    products = mapper[pgroup][0].objects.all()
    return render(request,"product/product.html",
                  {"productId":0, 
                   'products':products,
                   "action":"add",
                    'form':form,
                   'pgroup':pgroup})

Sales/templates/sales/getproductform.html
<label for="pgroup">Product Group</label>
<select name="pgroup" id="pgroup">
    <option value=""></option>
    {% for pgroup in product_groups  %}
    <option value="{{pgroup}}">{{pgroup}}</option>
    {% endfor %}
</select>

<label for="gender">Gender</label>
<select name="gender" id="gender">
    <option value=""></option>
    {% for gender in genders  %}
    <option value="{{gender}}">{{gender}}</option>
    {% endfor %}
</select>

<label for="age_group">Age Group</label>
<select name="age_group" id="age_group">
    <option value=""></option>
    {% for age_group in age_groups  %}
    <option value="{{age_group}}">{{age_group}}</option>
    {% endfor %}
</select>

<label for="product_type">Product Type</label>
<input type="text" name="product_type" id="product_type" required>
<label for="brabd">Brand</label>
<input type="text" name="brand" id="brand" required>
<label for="type">Type</label>
<input type="text" name="type" id="type" required>
<label for="color">Color</label>
<input type="text" name="color" id="color" required>

Sales/templates/sales/orderhistory.html
{% extends 'sales/sales.html' %} {% block title %} {% load static %}
<title>Product</title>{% endblock title %} {% block main %}

<section class="orderhistory">
    {% for order in orders %}
    <div class="order">
        <p>{{order.orderId}}</p>
    </div>
    {% endfor %}
</section>

{% endblock main %} {% block javascript %}
<script src="{% static 'javascript/state.js' %}"></script>
<script src="{% static 'javascript/productpage.js' %}"></script>
{% endblock javascript %}

Sales/templates/sales/product.html
{% extends 'sales/sales.html' %} {% block title %} {% load static %}
<title>Product</title>{% endblock title %} {% block main %}

<section id='list_items' class="list_items">
    {% for category in categories %}
    <div class="categories">
        <h3>{{category}}</h3>
        <div class="content">
            {% for productType in category.category.all %}
            <p class="innerItem"><a href="{% url 'sales:salesProductView' productType.id productType.p_group 'default' %}"> {{productType.name}} </a>
            </p>
            {% endfor %}
        </div>
    </div>
    {% endfor %}
</section>

{% if productType %}
  <h3>{{productTypeName.name}} {{productTypeName.category.name}}</h3>
<section id='list_items' class="list_items">
    {% for brand in brands %}
    <div class="categories">
        <div class="content">
                 <p class="innerItem"><a href="{% url 'sales:salesProductView' productType pgroup brand.brand %}"> {{brand.brand}} </a>
            
        </div>
    </div>
    {% endfor %}
</section>
{% endif %}

<div class="product_container">
    {% if products %} {% for product,sizes in products %}
    
    {% if sizes %}
        {% include 'sales/product_template.html' %}
    {% endif %}
        
    {% endfor %}
     {% elif initial %}
    {% comment %} <p>Please select a product type</p> {% endcomment %}
    {% else %}
    <p>No product Found</p>
    {% endif %}
</div>

{% comment %} <div style="margin: 30px 0px;" class="get_user">
    <label for="user_phone_number">Phone_Number</label>
    <input type="text" name="user_phone_number" id="user_phone_number">
    <button class="addbutton" id="get_user">Get User</button>
</div> {% endcomment %}

{% comment %} <div id="flex_container">
    <form action="{% url 'sales:salesView' %}" method="post">
        {% csrf_token %}
        {% include 'sales/getproductform.html' %}
        <button class="addbutton" type="submit">Get Product</button>
    </form>

    <div class="get_user">
        <label for="user_phone_number">Phone_Number</label>
        <input type="text" name="user_phone_number" id="user_phone_number">
        <button class="addbutton" id="get_user">Get User</button>
    </div>
</div> {% endcomment %}

{% include "sales/salesform.html" %} {% endblock main %} {% block javascript %}
<script src="{% static 'javascript/state.js' %}"></script>
<script src="{% static 'javascript/productpage.js' %}"></script>
<script>
    const data_ = document.getElementById('json_data').textContent
    const data = JSON.parse(data_)
    const pgroup = "{{pgroup}}"
    
    storestate = storeReducer(addProduct({products:data.products,pgroup}))
   // data.products.forEach(product =>{
      //  let target = document.getElementById(`meta-${product.id}`)
      //  target.innerHTML = product.meta
   // })

    setState(storestate)
</script>
{% endblock javascript %}

Sales/templates/sales/sales.html
 {% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" type="text/css" href="{% static 'CSS/administration.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'CSS/general.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'CSS/productpage.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'CSS/loader.css' %}">{% block styles %} {% endblock styles %}
    <link rel="shortcut icon" href="{% static 'CSS/logo.png' %}" type="image/png">
    <link rel="apple-touch-icon" href="{% static 'CSS/logo.png' %}">
    <link rel="icon" href="{% static 'CSS/logo4.png' %}" type="image/png"> {% block title %}
    <title>Sales</title>
    {% endblock title %}
    <meta name="author" content="Emeka Casper Onwuepe " />
    <meta name="description" content="" />
    <meta name="keywords" content=" " />
    <meta name="author" content="Emeka Casper Onwuepe " />
    <meta property="og:url" content="{{request.build_absolute_uri}}" />
    <meta property="og:type" content="" />
    <meta property="og:title" content="" />
    <meta property="og:description" content="" />
</head>

<body>
    <div id="bigwrapper">
        <header>
            <section class="menu">
                <div id="toggle" class="toggle">
                    <span></span>
                    <span></span>
                    <span class="last"></span>
                </div>
                <div id="logo-div">
                    <a href="{% url 'sales:salesView' %}"> <img class="logo" src="{% static 'CSS/logo.png' %}" alt="logo" width="100%"></a>
                </div>
                <div class="nav_and_user">
                    <div class="user">
                        {{request.user}}
                    </div>
                    <nav id="nav" class="nav">
                        {% block nav %} {% block log-control %}
                        <div class="logControl">
                            {% if not request.user.is_anonymous %}
                            <form action="{% url 'user:logoutView' %}" method="post">
                                {% csrf_token %}
                                <button class="logout" type="submit">Logout</button>
                            </form>
                            {% else %}
                            <a href="{% url 'user:loginView' %}"><button class="logout login" type="submit">LOGIN</button></a> {% endif %}
                        </div>
                        {% endblock log-control %} {% endblock nav %}
                    </nav>
                </div>
            </section>
        </header>

        <div class="adminWrapper">
            <aside>
                {% if not request.user.is_anonymous %}
                
                <div class="sideNav" id="sideNav">
                    <a href="javascript:void(0)" id="close" class="close">&times;</a>
                    <nav>
                        {% if request.user.is_admin %}
                        <a href="{% url 'badproduct:badProductView' 0 'view' 'product' %}">Bad Product</a>
                        <a href="{% url 'returnedproduct:returnedProductView' 0 'view' 'product' %}">Returned Product</a>
                        <a href="{% url 'branch:branchView' 0 'view' %}">Branches</a>
                        {% comment %} <a href="{% url 'product:categoryView' 0 'view' %}">Category</a> {% endcomment %}
                        {% comment %} <a href="{% url 'product:productTypeView' 0 'view' %}">Product Type</a> {% endcomment %}
                        {% comment %} <a href="{% url 'product:productView' 0 'view' 'product' %}">Products</a> {% endcomment %}
                        {% endif %}
                        <a href="{% url 'credit_sales:creditSalesView' 0 'view' %}">Credit Sales</a>
                        <a href="{% url 'user:customerView' 0 'view' %}">Customers</a>
                        {% if request.user.is_admin %}
                        <a href="{% url 'logistics:locationView' 0 'view' %}">Locations</a>
                        {% endif %}
                        {% comment %} <a href="{% url 'preOrder:preOrderView' 0 'view' %}">Pre Order</a> {% endcomment %}
                       
                        <a href="{% url 'sales:salesView' %}">Sales</a>
                        <a href="{% url 'sales:salesAnalysisView' 0 'default' %}">Sales Analysis</a>
                        {% if request.user.is_admin %}
                        {% comment %} <a href="{% url 'product:sizeView' 0 'view' %}">Size</a> {% endcomment %}
                        {% comment %} <a href="{% url 'user:userView' 0 'view' %}">Users</a> {% endcomment %}
                        <a href="{% url 'stock:getStockView' %}">Check Stock</a>
                        {% comment %} <div>
                            <p>Add Products</p>
                            {% for group in  product_groups %}
                            
                            {% endfor %} {% endcomment %}
                        {% comment %} </div> {% endcomment %}
                        {% comment %} <div class="stock_branches">
                            <p>Branch Stocks</p>
                            {% for branch in branches %}
                            {% for group in  product_groups %}
                            <a href="{% url 'stock:stockView' 0 branch.id 'view' group  %}">{{branch}} Branch <br/> {{group}} Stock</a> 
                            {% endfor %}
                            {% endfor %}
                        </div> {% endcomment %}
                        <div class="stock_branches">
                            <p>Add Branch Stocks</p>
                            {% for branch in branches %}
                            <a href="{% url 'stock:stockView' 0 branch.id 'view' 'product'  %}">{{branch}} Branch </a> 
                            {% endfor %}
                        </div>    
                        {% endif %}
                    </nav>
                </div>
                {% endif %}
            </aside>
            <main>    
                {% if not request.user.is_anonymous  %}
                <div class="user2">
                    {{request.user}}
                </div>
                {% endif %}
                {% block main %}
                   
                {% comment %} 
                    <form action="{% url 'sales:salesView' %}" method="post">
                        {% csrf_token %}
                        {% include 'sales/getproductform.html' %}
                        <button class="addbutton" type="submit">Get Product</button>
                    </form> {% endcomment %}
                

                <div class="product_container">

                    {% if not initial and not found %}
                    <p class="error">No Product Found</p>
                    {% elif not initial and found %} {% for product in products %} {% include "sales/product_template.html" %} {% endfor %} {% endif %}
                </div>

                <section class="list_items">
                    {% for category in categories %}
                    <div class="categories">
                        <h3>{{category}}</h3>
                        <div class="content">
                            {% for productType in category.category.all %}
                            <p class="innerItem"><a href="{% url 'sales:salesProductView' productType.id productType.p_group 'default' %}"> {{productType.name}} </a>
                            </p>
                            {% endfor %}
                        </div>
                    </div>
                    {% endfor %}
                </section> 

                {% include "sales/salesform.html" %} {% endblock main %}
            </main>

            <div id="loaderContainer" class="container">
                <div class="loader">
                    <span></span>
                    <span></span>
                    <span></span>
                </div>
            </div>

            <div id="backToTop" class="backToTop">
                <a href="#">&#10094;</a>
            </div>

        </div>
        <footer>
            {% block footer %}
            <footer>
                <p id="footer"> Copyright &copy;
                    <span id="footerdate" style="padding: 0%"></span>. All rights reserved. Smbclassicwears.com.ng
                    <br /> Designed by <a href="">CashTech</a>. </p>
            </footer>
            {% endblock footer %}
        </footer> 
    </div>
    {{json_data|json_script:'json_data'}}
    {% block javascript %}
    
    <script src="{% static 'javascript/state.js' %}"></script>
    <script src="{% static 'javascript/productpage.js' %}"></script>
    <script>
        const data_ = document.getElementById('json_data').textContent
        const data = JSON.parse(data_)
        const pgroup = "{{pgroup}}"
        storestate = storeReducer(addProduct({products:data.products,pgroup}))
        setState(storestate)
    </script>
    {% endblock javascript %}
    <script src="{% static 'javascript/generalAd.js' %}"></script>

</body>

</html>