Product/urls.py
from rest_framework import routers
from knox import views as KnoxView
from django.urls import path
from .import views
router = routers.DefaultRouter()


app_name="product"

urlpatterns = [ 
    path('cat/<int:categoryId>/<str:action>',views.categoryView,name="categoryView"), 
    path('producttype/<int:productTypeId>/<str:action>',views.productTypeView,name="productTypeView"), 
    path('size/<int:sizeId>/<str:action>',views.sizeView,name="sizeView"),
    path('product/<int:productId>/<str:action>/<str:pgroup>',views.productView,name="productView"),  
    # path('returnedproduct/<int:returnedProductId>/<str:action>',views.returnedProductView,name="returnedProductView"),  

]
urlpatterns += router.urls

Returned_Product/urls.py
from rest_framework import routers
from knox import views as KnoxView
from django.urls import path
from .import views
router = routers.DefaultRouter()


app_name="returnedproduct"

urlpatterns = [  
    path('<int:returnedProductId>/<str:action>/<str:pgroup>',views.returnedProductView,name="returnedProductView"),  

]
urlpatterns += router.urls

api/urls.py
from rest_framework import routers
from django.urls import path
from knox import views as KnoxView

from api.views import (Get_All, Get_Branch,processSalesView,
                       LoginUser,creditPaymentView,addProductView,
                       addStockView,PublishView)
router = routers.DefaultRouter()

app_name = 'api'

urlpatterns = [
    path('getall', Get_All.as_view(), name="get_all"),
    path('getbranch', Get_Branch.as_view(), name="get_branch"),
    path('logout', KnoxView.LogoutView.as_view(), name="knox_logout"),
    path('process',processSalesView.as_view(),name="processSalesView"),
    path('login', LoginUser.as_view(), name="login"),
    path('creditpayment',creditPaymentView.as_view(),name='creditPayment'),
    path('addproduct',addProductView.as_view(),name='addProductView'),
    path('addstock',addStockView.as_view(),name='addstockView'),
    path('publish',PublishView.as_view(),name='PublishView')
    
           
]

urlpatterns += router.urls

sales_and_stock/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('',include("Frontview.urls" , namespace='frontview')),
    path('admin/', admin.site.urls),
    path('logistics/',include("Logistics.urls" , namespace='logistics')),
    path('user/',include("User.urls" , namespace='user')),
    path('api/',include("api.urls" , namespace='api')),
    path('branch/',include("Branch.urls", namespace='branch')),
    path('product/',include("Product.urls",namespace='product')),
    path('badproduct/',include("Bad_Product.urls",namespace='bad_product')),
    path('returnedproduct/',include("Returned_Product.urls",namespace='returned_product')),
    path('stock/',include("Stock.urls",namespace='stock')),
    path('sales/',include("Sales.urls",namespace='sales')),
    path('credits/',include("Credit_Sales.urls",namespace='credit_sales')),
    path('password_reset/',auth_views.PasswordResetView.as_view(template_name="user/passwordreset.html"),name='password_reset',),
    path('password_reset_done/',auth_views.PasswordResetView.as_view(template_name="user/password_reset_done.html"),name="password_reset_done",),
    path('password_reset_confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name="user/password_reset_confirm.html"), name='password_reset_confirm',),
    path( 'password_reset_completed/',auth_views.PasswordResetCompleteView.as_view(template_name="user/password_reset_complete.html"), name='password_reset_complete',),

]

urlpatterns+=staticfiles_urlpatterns()

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# handler404 = 'errortemplate.views.page_not_found'
# handler403 = 'errortemplate.views.permission_denied'
# handler400 = 'errortemplate.views.bad_request'

Returned_Product/models.py
from django.db import models
from Branch.models import Branch

from Product.models import Foot_Wear, Product, Size, Suit, Top


# Create your models here.

class Returned_Product_Abstract(models.Model):
    """Model definition for Returned_Product_Abstract."""

    # TODO: Define fields here
    qty = models.IntegerField("qty",null=False,blank=False)
    unit_price = models.DecimalField("unit_price", max_digits=50, decimal_places=2,null=False,blank=False)
    total_price = models.DecimalField("total_price", max_digits=50, decimal_places=2,null=False,blank=False) 
    date_of_purchase = models.DateField("date_of_purchase", auto_now=False, auto_now_add=False,null=False,blank=False)
    date_of_return = models.DateTimeField("date_of_return", auto_now=False, auto_now_add=False,null=False,blank=False)

    class Meta:
        """Meta definition for Returned_Product_Abstract."""
        abstract = True

      

class Returned_Product(Returned_Product_Abstract):
    """Model definition for Returned_Product."""

    # TODO: Define fields here
    product = models.ForeignKey(Product, on_delete=models.CASCADE,related_name = "returned_product_product_type")
    branch = models.ForeignKey(Branch, on_delete=models.CASCADE, related_name="returned_product_branch")
    size_instance = models.ForeignKey(Size, verbose_name="size_instance", on_delete=models.CASCADE,
                        related_name="returned_product_size_instance",null=True, blank=True)

    class Meta:
        """Meta definition for Returned_Product."""

        verbose_name = 'Returned_Product'
        verbose_name_plural = 'Returned_Products'

    def __str__(self):
        """Unicode representation of Returned_Product."""
        return f" {self.branch} - {self.product} - {self.total_price}"
    
    
class Returned_Suit(Returned_Product_Abstract):
    """Model definition for Returned_Suit."""

    # TODO: Define fields here
    product = models.ForeignKey(Suit,verbose_name='suit',
                                on_delete=models.CASCADE,related_name = "Returned_Suit_product_type")
    branch = models.ForeignKey(Branch, on_delete=models.CASCADE, related_name="Returned_Suit_branch")
    size_instance = models.ForeignKey(Size, verbose_name="size_instance", on_delete=models.CASCADE,
                        related_name="Returned_Suit_size_instance",null=True, blank=True)

    class Meta:
        """Meta definition for Returned_Suit."""

        verbose_name = 'Returned_Suit'
        verbose_name_plural = 'Returned_Suits'

    def __str__(self):
        """Unicode representation of Returned_Suit."""
        return f" {self.branch} - {self.product} - {self.total_price}"
    
class Returned_Top(Returned_Product_Abstract):
    """Model definition for Returned_Top."""

    # TODO: Define fields here
    product = models.ForeignKey(Top,verbose_name='top'
                                , on_delete=models.CASCADE,related_name = "Returned_Top_product_type")
    branch = models.ForeignKey(Branch, on_delete=models.CASCADE, related_name="Returned_Top_branch")
    size_instance = models.ForeignKey(Size, verbose_name="size_instance", on_delete=models.CASCADE,
                        related_name="Returned_Top_size_instance",null=True, blank=True)
    

    class Meta:
        """Meta definition for Returned_Top."""

        verbose_name = 'Returned_Top'
        verbose_name_plural = 'Returned_Tops'

    def __str__(self):
        """Unicode representation of Returned_Top."""
        return f" {self.branch} - {self.product} - {self.total_price}"
    
class Returned_Foot_Wear(Returned_Product_Abstract):
    """Model definition for Returned_Foot_Wear."""

    # TODO: Define fields here
    product = models.ForeignKey(Foot_Wear,verbose_name='foot_wear'
                                , on_delete=models.CASCADE,related_name = "returned_foot_wear_product_type")
    branch = models.ForeignKey(Branch, on_delete=models.CASCADE, related_name="returned_foot_wear_branch")
    size_instance = models.ForeignKey(Size, verbose_name="size_instance", on_delete=models.CASCADE,
                        related_name="returned_foot_wear_size_instance",null=True, blank=True)
    

    class Meta:
        """Meta definition for Returned_foot_wear."""

        verbose_name = 'Returned_Foot_Wear'
        verbose_name_plural = 'Returned_Foot_Wears'

    def __str__(self):
        """Unicode representation of Returned_Foot_Wear."""
        return f" {self.branch} - {self.product} - {self.total_price}"

Product/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from Branch.models import Branch, Product_Size
from Product.forms import  CategoryForm, FootWearForm, ProductForm, ProductTypeForm,  SizeForm, SuitForm, TopForm
from Product.models import Category, Foot_Wear, Product, Product_Type, Size, Suit, Top

# Create your views here.
@login_required(login_url="user:loginView")
def categoryView(request,categoryId,action):
    
    # categories = Category.objects.all()
    
    if categoryId != 0:   
        category_instance = Category.objects.get(id=categoryId)
    
    if request.method == "POST" and action == "add":
        form = CategoryForm(data= request.POST,files=request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('product:categoryView',
            kwargs={"action":"view","categoryId":0}))
        else:
            return render(request,"product/category.html",
                  {"form":form,"categoryId":0})  
            
    if action == "edit":
        if request.method == "POST":
            form = CategoryForm(data= request.POST,files=request.FILES,instance=category_instance)
         
            if form.is_valid():
                form.save()
                return HttpResponseRedirect(reverse('product:categoryView',
                        kwargs={"action":"view","categoryId":0}))
            else:
                return render(request,"product/category.html",
                  {"form":form,"categoryId":category_instance.id})
        else:
            return render(request,"product/category.html",
                  {"form":CategoryForm(instance=category_instance),
                   "categoryId":category_instance.id,"action":"edit",
                #    'categories':categories
                   })
    
    if action == "delete":
        category_instance.delete()
        return HttpResponseRedirect(reverse('product:categoryView',
            kwargs={"action":"view","categoryId":0}))
                 
    return render(request,"product/category.html",
                  {"form":CategoryForm(),"categoryId":0, 
                #    'categories':categories,
                   "action":"add"})
    

@login_required(login_url="user:loginView")
def productTypeView(request,productTypeId,action):
    
    productTypes = Product_Type.objects.all()
    
    if productTypeId != 0:   
        product_type_instance = Product_Type.objects.get(id=productTypeId)
    
    if request.method == "POST" and action == "add":
        form = ProductTypeForm(data= request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('product:productTypeView',
            kwargs={"action":"view","productTypeId":0}))
        else:
            return render(request,"product/product_type.html",
                  {"form":form,"productTypeId":0,"action":"view"})  
            
    if action == "edit":
        if request.method == "POST":
            form = ProductTypeForm(data= request.POST,instance=product_type_instance)
            if form.is_valid():
                form.save()
                return HttpResponseRedirect(reverse('product:productTypeView',
                        kwargs={"action":"view","productTypeId":0}))
            else:
                return render(request,"product/product_type.html",
                  {"form":form,"productTypeId":product_type_instance.id})
        else:
            return render(request,"product/product_type.html",
                  {"form":ProductTypeForm(instance=product_type_instance),
                   "productTypeId":product_type_instance.id,"action":"edit",'productTypes':productTypes})
    
    if action == "delete":
        product_type_instance.delete()
        return HttpResponseRedirect(reverse('product:productTypeView',
            kwargs={"action":"view","productTypeId":0}))
                 
    return render(request,"product/product_type.html",
                  {"form":ProductTypeForm(),"productTypeId":0, 'productTypes':productTypes,"action":"add"})
  
    
@login_required(login_url="user:loginView")  
def sizeView(request,sizeId,action):
    
    sizes = Size.objects.all()
    form = SizeForm()
    
    if sizeId != 0:   
        size_instance = Size.objects.get(id=sizeId)
       
    
    if request.method == "POST" and action == "add":
        form = SizeForm(data= request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('product:sizeView',
            kwargs={"action":"view","sizeId":0}))
        else:
            return render(request,"product/size.html",
                  {"form":form,"sizeId":0,"action":"view"})  
            
    if action == "edit":
        if request.method == "POST":
            form = SizeForm(data= request.POST,instance=size_instance)
            if form.is_valid():
                form.save()
                return HttpResponseRedirect(reverse('product:sizeView',
                        kwargs={"action":"view","sizeId":0}))
            else:
                return render(request,"product/size.html",
                  {"form":form,"sizeId":size_instance.id,"action":"edit",'sizes':sizes})
        else:
            return render(request,"product/size.html",
                  {"instance":size_instance,
                   "sizeId":size_instance.id,"action":"edit",'sizes':sizes})
    
    if action == "delete":
        size_instance.delete()
        return HttpResponseRedirect(reverse('product:sizeView',
            kwargs={"action":"view","sizeId":0}))
                 
    return render(request,"product/size.html",
                  {"form":form,"sizeId":0, 'sizes':sizes,"action":"add"})
    

@login_required(login_url="user:loginView")
def productView(request,productId,action,pgroup):
    mapper = {'product':[Product,ProductForm],
              'suits':[Suit,SuitForm],
              'top':[Top,TopForm],
              'foot_wear':[Foot_Wear,FootWearForm],
    
              }
    
    form = mapper[pgroup][1]()
    
    if productId != 0:   
        product_instance = mapper[pgroup][0].objects.get(id=productId)
        form = mapper[pgroup][1](instance=product_instance)
        
    if request.method == "POST" and action == "add":
        form = mapper[pgroup][1](data= request.POST,files=request.FILES)
        if form.is_valid():
            form.save()
            # product.sizes.all()
            return HttpResponseRedirect(reverse('product:productView',
            kwargs={"action":"view","productId":0,'pgroup':pgroup}))
        else:
            return render(request,"product/product.html",
                  {"form":form,"productId":0,"action":"add",
                   'pgroup':pgroup})  
            
    if action == "edit" and request.method == "POST":
            
        form = mapper[pgroup][1](data= request.POST,files=request.FILES,instance=product_instance)
        if form.is_valid():
            form.save()

            return HttpResponseRedirect(reverse('product:productView',
                        kwargs={"action":"view","productId":0,'pgroup':pgroup}))
        else:
            return render(request,"product/product.html",
                  {"form":form,"productId":product_instance.id,
                   "action":"edit",'pgroup':pgroup})
    elif action == "edit" and request.method == "GET":
        return render(request,"product/product.html",
                  {"product_instance":product_instance,
                   "productId":product_instance.id,"action":"edit",
                   'form':form,
                    'pgroup':pgroup})
    
    if action == "delete":
        product_instance.delete()
        return HttpResponseRedirect(reverse('product:productView',
            kwargs={"action":"view","productId":0,'pgroup':pgroup}))
                 
    products = mapper[pgroup][0].objects.all()
    return render(request,"product/product.html",
                  {"productId":0, 
                   'products':products,
                   "action":"add",
                    'form':form,
                   'pgroup':pgroup})

Product/templates/product/category.html
{% extends 'sales/sales.html' %} {% block title %}
<title>Category</title>{% endblock title %} {% block main %}
<h1>Category</h1>
<form style="margin-bottom: 30px;" enctype="multipart/form-data" action="{% url 'product:categoryView' categoryId action %}" method="post">
    {% csrf_token %} {{form}}
    <button class="addbutton" type="submit">
        
        {% if action == "add" %}
            ADD
        {% else %}
            UPDATE
        {% endif %}
            
    </button>
</form>
<section class="list_items">

    {% for category in categories %}
    <div class="items ">
        <div class="innerItem">
        <p class="description" style="margin-right:20px;">{{category.name}}</p>

        {% comment %} <a class="delete" href="{% url 'product:categoryView' category.id 'delete' %}"> <button>Delete</button></a> {% endcomment %}
        <a href="{% url 'product:categoryView' category.id 'edit' %}"> <button>Edit</button></a>
        </div>
    </div>
    {% endfor %}

</section>
{% endblock main %}

Product/templates/product/product.html
{% extends 'sales/sales.html' %} {% block title %}
<title>Product</title>{% endblock title %} {% block main %}
<h1>{{pgroup|upper}}</h1>

<section style="text-align: center;" class="list_items">
    {% for pgroup in product_groups  %}
    <div class="items">

        <a href="{% url 'product:productView' productId action pgroup %}">{{pgroup}}</a>
    </div>

    {% endfor %}
</section>

<form action="{% url 'product:productView' productId action pgroup %}" enctype="multipart/form-data" method="post">
    {% csrf_token %}
    {{form}}
    <button type="submit" class='addbutton'>
        
        {% if action == "add" %}
            ADD
        {% else %}
            UPDATE
        {% endif %}
            
    </button>
</form>



{% comment %} <form action="/product/product/0/add" enctype="multipart/form-data" method="post">

</form> {% endcomment %}



<section class="list_items">
    {% for product in products %}
    <div class="items center">
        <p class='description'>{{product}}</p>

        {% comment %} <a class="delete" href="{% url 'product:productView' product.id 'delete' pgroup %}"><button>Delete</button></a>  {% endcomment %}
        <a href="{% url 'product:productView' product.id 'edit' pgroup %}"><button>Edit</button></a>
    </div>
    {% endfor %}
</section>

{% endblock main %}

Product/templates/product/product_type.html
{% extends 'sales/sales.html' %} {% block title %}
<title>Product Type</title>{% endblock title %} {% block main %}
<h1>Product Type</h1>
<form action="{% url 'product:productTypeView' productTypeId action %}" method="post">
    {% csrf_token %} {{form}}
    <button type="submit" class="addbutton">
        
        {% if action == "add" %}
            ADD
        {% else %}
            UPDATE
        {% endif %}
            
    </button>
</form>

<section class="list_items">
    {% for productType in productTypes %}
    <div class="items ">
        <div class="innerItem">
        <p class="description" style="margin-right:20px;">{{productType}}</p>

        {% comment %} <a class="delete" href="{% url 'product:productTypeView' productType.id 'delete' %}"><button>Delete</button></a> {% endcomment %}
        <a href="{% url 'product:productTypeView' productType.id 'edit' %}"><button>Edit</button></a>
        </div>
    </div>
    {% endfor %}

</section>
{% endblock main %}

Product/templates/product/returnedproduct.html
{% extends 'sales/sales.html' %} {% load static %} {% block title %}
<title>Returned Product</title>{% endblock title %} {% block main %}
<h1>Returned Products</h1>

<form name="Form" action="{% url 'product:returnedProductView' returnedProductId action %}" method="post">
    {% csrf_token %} {% if action == "add" %}
    <label for="id_product">Product:</label>
    <select name="product" required="" id="id_product">
        <option value="" selected="">---------</option>
        {% for product in request.user.branch.products_branches.all  %}
        
        {% if product.multipleSIzes %}
         
         {% for size  in product.multipleSIzes.all  %}
         <option value="{{product.id}}-{{size.id}}">{{product.product_type.name}} - {{product.color}} - &#8358 <span class="amount">{{size.price}}</span> - size:{{size.size}}</option>
         {% endfor %}    
            
        {% else %}
        <option value="{{product.id}}">{{product.product_type.name}} - {{product.color}} - &#8358 <span class="amount">{{product.price}}</span> - size:{{product.size}}</option>
        {% endif %} 
        {% endfor %}
</select> {% else %}
    <label for="id_product">Product:</label>
    <input type="text" name="product" value="{{instance.product.product_type}}" id="id_product" readonly>

    <label for="id_size_instance">Size_instance:</label>
    <input type="text" name="size_instance" value="{{instance.size_instance}}" id="id_size_instance" readonly> {% endif %}

    <input type="hidden" name="branch" value="{{request.user.branch_id}}">

    <label for="id_qty">Qty:</label>
    <input type="number" name="qty" required="" id="id_qty" value="{{instance.qty}}">
    <label for="id_unit_price">Unit_price:</label>
    <input type="text" name="unit_price" required="" id="id_unit_price" value="{{instance.unit_price}}">
    <label for="id_total_price">Total_price:</label>
    <input type="text" name="total_price" required="" id="id_total_price" value="{{instance.total_price}}">
    <label for="id_date_of_purchase">Date_of_purchase:</label>
    <input type="date" name="date_of_purchase" required="" id="id_date_of_purchase" value="{{instance.date_of_purchase|date:'Y-m-d'}}">
    <label for="id_date_of_return">Date_of_return: </label>
    <input type="date" name="date_of_return" required="" id="id_date_of_return" value="{{instance.date_of_return|date:'Y-m-d'}}">
    <button id="button" class='addbutton' type="submit">
        
        {% if action == "add" %}
            ADD
        {% else %}
            UPDATE
        {% endif %}
            
    </button>
</form>

{% for branch in branches %}
<h3 class="reduceMarginBottom">{{branch}}</h3>
<section class="list_items">
    {% for returnedProduct in branch.returned_product_branch.all %}
    <div class="items center">
        {% if returnedProduct.size_instance %}
        <p class="description">{{returnedProduct.branch}} - {{returnedProduct.product.product_type}} - {{returnedProduct.product.color}} - {{returnedProduct.size_instance.size}} - ({{returnedProduct.date_of_return|date:'Y-m-d'}}) - {{returnedProduct.qty}} - &#8358 <span class="amount">{{returnedProduct.total_price}}</span>
        </p>
        {% else %}
        <p class="description">{{returnedProduct.branch}} - {{returnedProduct.product}} - ({{returnedProduct.date_of_return|date:'Y-m-d'}}) - {{returnedProduct.qty}} - &#8358
            <span class="amount">{{returnedProduct.total_price}}</span></p>
        {% endif %}
        <a class="delete" href="{% url 'product:returnedProductView' returnedProduct.id 'delete' %}"><button>Delete</button></a>
        <a href="{% url 'product:returnedProductView' returnedProduct.id 'edit' %}"><button>Edit</button></a>
    </div>
    {% endfor %}
</section>
{% endfor %} {% endblock main %} {% block javascript %}
<script src="{% static 'javascript/returnedProduct.js' %}"></script>
{% endblock javascript %}

Product/templates/product/size.html
{% extends 'sales/sales.html' %} {% block title %}
<title>Sizes</title>{% endblock title %} {% block main %}

<h1>Sizes</h1>

<form action="{% url 'product:sizeView' sizeId action %}" method="post">
    {% csrf_token %} 
   {{form}}
    <button type="submit" class='addbutton'>
        
        {% if action == "add" %}
            ADD
        {% else %}
            UPDATE
        {% endif %}
            
    </button>
</form>

<section class="list_items">
    {% for size in sizes %}
    <div class="items">
        <div class="innerItem">
        <p class="description" style="margin-right:20px;">{{size}}</p class="description">

        {% comment %} <a class="delete" href="{% url 'product:sizeView' size.id 'delete' %}"><button>Delete</button></a> {% endcomment %}
        <a href="{% url 'product:sizeView' size.id 'edit' %}"><button>Edit</button></a>
        </div>
    </div>
    {% endfor %}
</section>

{% endblock main %}