Credit_Sales/urls.py
from rest_framework import routers
from django.urls import path
from .import views
router = routers.DefaultRouter()


app_name="credit_sales"

urlpatterns = [ 
    path('<int:customerID>/<str:action>',views.creditSalesView,name="creditSalesView"), 
    path('payment/<int:creditId>/<str:action>',views.paymentView,name="paymentView"), 
]
urlpatterns += router.urls

Sales/urls.py
from rest_framework import routers
from django.urls import path

from .import views
router = routers.DefaultRouter()


app_name="sales"

urlpatterns = [ 
    path('',views.salesView,name="salesView"), 
    path('process',views.processSalesView,name="processSalesView"),
    path('<int:productTypeId>/<str:pgroup>/<str:brand>',views.salesProductView,name="salesProductView"),
    path('sale/<str:purchaseId>/<str:type>',views.saleView,name="saleView"), 
    path('analysis/<int:branchID>/<str:date>/',views.salesAnalysisView,name="salesAnalysisView"),
    path('<str:start_date>/<str:end_date>/<int:branchID>/rangeanalysis',views.rangeSalesView,name="rangeSalesView"),

]
urlpatterns += router.urls

api/urls.py
from rest_framework import routers
from django.urls import path
from knox import views as KnoxView

from api.views import (Get_All, Get_Branch,processSalesView,
                       LoginUser,creditPaymentView,addProductView,
                       addStockView,PublishView)
router = routers.DefaultRouter()

app_name = 'api'

urlpatterns = [
    path('getall', Get_All.as_view(), name="get_all"),
    path('getbranch', Get_Branch.as_view(), name="get_branch"),
    path('logout', KnoxView.LogoutView.as_view(), name="knox_logout"),
    path('process',processSalesView.as_view(),name="processSalesView"),
    path('login', LoginUser.as_view(), name="login"),
    path('creditpayment',creditPaymentView.as_view(),name='creditPayment'),
    path('addproduct',addProductView.as_view(),name='addProductView'),
    path('addstock',addStockView.as_view(),name='addstockView'),
    path('publish',PublishView.as_view(),name='PublishView')
    
           
]

urlpatterns += router.urls

sales_and_stock/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('',include("Frontview.urls" , namespace='frontview')),
    path('admin/', admin.site.urls),
    path('logistics/',include("Logistics.urls" , namespace='logistics')),
    path('user/',include("User.urls" , namespace='user')),
    path('api/',include("api.urls" , namespace='api')),
    path('branch/',include("Branch.urls", namespace='branch')),
    path('product/',include("Product.urls",namespace='product')),
    path('badproduct/',include("Bad_Product.urls",namespace='bad_product')),
    path('returnedproduct/',include("Returned_Product.urls",namespace='returned_product')),
    path('stock/',include("Stock.urls",namespace='stock')),
    path('sales/',include("Sales.urls",namespace='sales')),
    path('credits/',include("Credit_Sales.urls",namespace='credit_sales')),
    path('password_reset/',auth_views.PasswordResetView.as_view(template_name="user/passwordreset.html"),name='password_reset',),
    path('password_reset_done/',auth_views.PasswordResetView.as_view(template_name="user/password_reset_done.html"),name="password_reset_done",),
    path('password_reset_confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name="user/password_reset_confirm.html"), name='password_reset_confirm',),
    path( 'password_reset_completed/',auth_views.PasswordResetCompleteView.as_view(template_name="user/password_reset_complete.html"), name='password_reset_complete',),

]

urlpatterns+=staticfiles_urlpatterns()

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# handler404 = 'errortemplate.views.page_not_found'
# handler403 = 'errortemplate.views.permission_denied'
# handler400 = 'errortemplate.views.bad_request'

Credit_Sales/models.py
from django.db import models
from Branch.models import Branch
from Sales.models import Items
from User.models import Customer

# Create your models here.
class Credit_Sale(models.Model):
    """Model definition for Credit_Sale."""

    # TODO: Define fields here
    branch = models.ForeignKey(Branch,related_name="credit_sale_branch", verbose_name="branch", on_delete=models.CASCADE)
    total_amount = models.DecimalField("total_amount", max_digits=10, decimal_places=2)
    expected_amount = models.DecimalField("expected_amount", max_digits=10, decimal_places=2)
    remark = models.CharField("remark", max_length=200)
    date = models.DateField("date", auto_now=False, auto_now_add=True)
    items = models.ManyToManyField(Items, verbose_name="items",related_name="credit_sale_Items")
    customer = models.ForeignKey(Customer, verbose_name="customer",related_name="credit_sale_customer",on_delete=models.CASCADE)
    purchase_id = models.CharField("purchase_id", max_length=150,unique=True)
    total_payment = models.DecimalField("total_payment",max_digits=10, decimal_places=2,default=0)
    balance = models.DecimalField("balance",max_digits=10, decimal_places=2,default=0)
    fully_paid = models.BooleanField("fully_paid",default=False)

    class Meta:
        """Meta definition for Credit_Sale."""

        verbose_name = 'Credit_Sale'
        verbose_name_plural = 'Credit_Sales'
        ordering = ["-date"]

    def __str__(self):
        """Unicode representation of Credit_Sale."""
        return f"{self.customer} - {str(self.total_amount)}"


class Payment(models.Model):
    """Model definition for Payment."""

    # TODO: Define fields here
    amount = models.DecimalField("amount", max_digits=10, decimal_places=2)
    date = models.DateField("date", auto_now=False, auto_now_add=True)
    credit_sale  = models.ForeignKey(Credit_Sale,verbose_name="credit_sale",
                                     related_name="payment_credit_sale", on_delete=models.CASCADE)
    class Meta:
        """Meta definition for Payment."""

        verbose_name = 'Payment'
        verbose_name_plural = 'Payments'

    def __str__(self):
        """Unicode representation of Payment."""
        return f"{self.credit_sale} - {str(self.amount)}"

Credit_Sales/forms.py
from django import forms
from .models import  Payment

class PaymentForm(forms.ModelForm):
    class Meta:
        model = Payment
        fields = ['amount']

Credit_Sales/views.py
from urllib import request
from coreapi import Object
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from Credit_Sales.forms import PaymentForm

from Credit_Sales.models import Credit_Sale, Payment
from User.models import Customer

# Create your views here.
@login_required(login_url="user:loginView")
def creditSalesView(request,customerID,action):
    credits = []
    message =None
    settled = False
    customerid = customerID
    
    if request.method == "POST":
        data = request.POST
        phone_number = data['phone_number']
        
        credits = Credit_Sale.objects.filter(
            customer__phone_number = phone_number, fully_paid=False )
        if not credits:
            message = "No unsettled debts found"
        
        try:
            customer = Customer.objects.get(phone_number = phone_number)
            customerid = customer.id
        except Customer.DoesNotExist:
            message = "No customer found. Please be sure the phone number is correct"
        
        
    if action == "settled" and customerID>0:
        credits =  Credit_Sale.objects.filter(
            customer = customerID, fully_paid=True ) 
        settled = True
        if not credits: 
            message = "No settled debts found" 
    
    if customerID>0 and action != "settled":
        credits =  Credit_Sale.objects.filter(
            customer = customerID, fully_paid=False ) 
        try:
            customer = Customer.objects.get(pk = customerID)
            customerid = customer.id
        except Customer.DoesNotExist:
            pass
        
        if not credits: 
            message = "No unsettled debts found" 
        
    return render(request,"credit_sales/credit.html",{"credits":credits,
                                                      "message":message,
                                                      "settled":settled,
                                                      'customerid':customerid}) 

@login_required(login_url="user:loginView")
def paymentView(request,creditId,action):
    
    previous_payments = None
    customer = None
    paymentId= None
    payment_instance = None
    credit_sale = None
    try:
        credit_sale = Credit_Sale.objects.get(id= creditId)
    except Credit_Sale.DoesNotExist:
        pass
    
    if action =="add" or action =='view':
        customer = Customer.objects.get(credit_sale_customer__id = creditId)
        previous_payments = Payment.objects.filter(credit_sale=creditId)
        
    if action == "edit" or action =='delete':
        paymentId = creditId
        payment_instance = Payment.objects.get(pk=paymentId)
        creditId = payment_instance.credit_sale.id
        customer = Customer.objects.get(credit_sale_customer__id = creditId)
        previous_payments = Payment.objects.filter(credit_sale=creditId)

    if request.method == "POST" and action == "add":
        form = PaymentForm(data= request.POST)
        if form.is_valid():
            amount = form.cleaned_data["amount"]
            credit_sale = Credit_Sale.objects.get(pk=creditId)
            Payment.objects.create(amount=amount,credit_sale=credit_sale)
            return HttpResponseRedirect(reverse('credit_sales:paymentView',
            kwargs={"action":"view","creditId":creditId}))
        else:
            return render(request,"credit_sales/payment.html",
                  {"form":form,"creditId":creditId,
                   'customer':customer,"previous_payments":previous_payments})  
            
    if action == "edit":
        if request.method == "POST":
            form = PaymentForm(data= request.POST,instance=payment_instance)
            if form.is_valid():
                form.save()
                return HttpResponseRedirect(reverse('credit_sales:paymentView',
                        kwargs={"action":"view","creditId":creditId}))
            else:
                return render(request,"credit_sales/payment.html",
                  {"form":form,"creditId":payment_instance.id,
                   'customer':customer,"previous_payments":previous_payments,
                   "credit_sale":credit_sale})
        else:
            return render(request,"credit_sales/payment.html",
                  {"form":PaymentForm(instance=payment_instance),
                   "creditId":payment_instance.id,"action":"edit",
                   'customer':customer,"previous_payments":previous_payments,
                   "credit_sale":credit_sale})
    
    if action == "delete":
        payment_instance.delete()
        return HttpResponseRedirect(reverse('credit_sales:paymentView',
            kwargs={"action":"view","creditId":creditId}))
    
    return render(request,"credit_sales/payment.html",
                      {"previous_payments":previous_payments,
                       "form":PaymentForm(),'creditId':creditId,"action":"add",
                       'customer':customer,"credit_sale":credit_sale})
        

Credit_Sales/templates/credit_sales/credit.html
 {% extends 'sales/sales.html' %} {% load static %} {% block title %}
<title>Credit</title>{% endblock title %} {% block main %}
<h1>Credit Sales</h1>
<form action="{% url 'credit_sales:creditSalesView' 0 'view' %}" method="post">
    {% csrf_token %}
    <label for="phone_number">Phone Number</label>
    <input type="text" name="phone_number" id="phone_number">
    <button type="submit" class="addbutton"> Get Credit Details </button>
</form>

<div>
    <p style="margin:10px 0px">{{credits.0.customer}}</p>
</div>


<div class="direction" style="margin: 0px 0px 10px 0px">
    {% if settled %}
    <a href="{% url 'credit_sales:creditSalesView' customerid 'view' %}">View Debts</a>
    <h3>Settled Debts</h3>
    {% endif %} {% if not settled and customerid != 0 %}
    <a href="{% url 'credit_sales:creditSalesView' customerid 'settled' %}">View Settled Payments</a>
    <h3>Debits</h3>
    {% endif %}

</div>

<div>

    {% if message %}
    <p>{{message}}</p>
    {% endif %}

</div>

{% if credits %}


<div id="salesList" style="margin: 0px auto;">
    <table>
        <thead>
            <th>SN</th>
            <th>Date</th>
            <th>Branch</th>
            <th>Purchase Id</th>
            <th>Total Amount</th>
            <th>Total Payment</th>
            <th>Balance</th>
        </thead>
        <tbody>
            {% for item in credits %}
            <tr>
                <td class="sn"></td>
                <td>{{item.date}}</td>
                <td>{{item.branch}}</td>
                <td><a href="{% url 'sales:saleView' item.purchase_id 'credit' %}">
                    {{item.purchase_id}}</a></td>
                <td class='amount'>{{item.total_amount}}</td>
                <td class="amount">{{item.total_payment}}</td>
                <td class="amount">{{item.balance}}</td>
                <td><a href="{% url 'credit_sales:paymentView' item.id 'view' %}">
                    Payments</a></td>
            </tr>
            {% endfor %}
        </tbody>
        <tfoot></tfoot>
    </table>
</div>
{% endif %} {% endblock main %} {% block javascript %}
<script src="{% static 'javascript/creditsales.js' %}"></script>
{% endblock javascript %}

Credit_Sales/templates/credit_sales/payment.html
{% extends 'sales/sales.html' %} {% load static %} {% block title %}
<title>Payment</title>{% endblock title %} {% block main %}
<h1>Payment</h1>
<div style="margin-bottom:20px" class="list_items">
    <p class="items"><a href="{% url 'credit_sales:creditSalesView' customer.id 'view' %}">{{customer.name}}</a></p>
    <p class="items"><label style="display: inline;">Amount: </label > <span>&#8358</span> <span class="amount">{{credit_sale.total_amount}}</span></p>
    <p class="items"><label style="display: inline;">Total Payment: </label> <span>&#8358</span> <span class="amount">{{credit_sale.total_payment}}</span></p>
    <p class="items"><label style="display: inline;">Balance: </label> <span>&#8358</span> <span class="amount">{{credit_sale.balance}}</span></p>
</div>

<div>
    <form action="{% url 'credit_sales:paymentView' creditId action %}" method="post">
        {% csrf_token %} {{form}}
        <button type="submit" class="addbutton">{% if action == "add" %}
            ADD
        {% else %}
            UPDATE
        {% endif %}</button>
    </form>
</div>

<section class="list_items">

    {% for previous_payment in previous_payments %}
    <div class="items center">
        <p class="description">{{previous_payment.date}} - &#8358<span class="amount">{{previous_payment.amount}}</span></p>

        <a class="delete" href="{% url 'credit_sales:paymentView' previous_payment.id 'delete' %}"><button>Delete</button></a>
        <a href="{% url 'credit_sales:paymentView' previous_payment.id 'edit' %}"> <button>Edit</button></a>
    </div>
    {% endfor %}

</section>
{% endblock main %} {% block javascript %}
<script src="{% static 'javascript/state.js' %}"></script>
<script src="{% static 'javascript/creditsales.js' %}"></script>
{% endblock javascript %}